services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=tmdb_db
      - TMDB_BASE_URL=https://api.themoviedb.org/3
      - TMDB_API_KEY=316818c2fe4f44ec9b99e4c364ff473b
      - SECRET_TOKEN=technicalassessmentsecretkey
volumes:
  mongodata: